version: '3'
services:
  pause:
    image: gcr.io/google_containers/pause-amd64:3.0
    networks:
      pause_vpc:
        ipv4_address: 192.168.168.2
    container_name: pause-192.168.168.2
    restart: always

networks:
  pause_vpc:
    name: pause_network
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.168.0/24
         gateway: 192.168.168.1
